---
- hosts: all
  become: yes
  vars:
    create_containers: 1
    default_container_name: bor
    default_container_image: "{{ lookup('env','ECR_IMAGE') }}"
  tasks:
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Login ECR
      shell: "{{ item }}"
      with_items: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
        unzip awscliv2.zip \
        sudo ./aws/install \
        aws ecr get-login --no-include-email --region us-east-1 
    - name: Pull default docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Create container
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        state: started
        ports: "8080:80"
      with_sequence: count={{ create_containers }}
    - name: Run container
      ansible.builtin.shell: sudo docker run -d {{ default_container_name }}
